name = "fpjs-metrics-beta"
type = "javascript"
account_id = ""
zone_id = ""
route = ""

[vars]
api_route = "/abcd1234"
api_for_script_download = "/ghjklmno56789"
api_for_get_endpoint = "/qwerty13579"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
