name = "fpjs-metrics-beta"
type = "javascript"

account_id = ""
zone_id = ""
route = ""
workers_dev = true

[vars]
api_route = "<BASE ENDPOINT FOR FPJS>"
api_for_script_download = "<SCRIPT DOWNLOADING SUB PATH>"
api_for_get_endpoint = "<GET ENDPOINT SUB PATH>"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
