name = "fpjs-metrics-beta"
type = "javascript"

account_id = ""
zone_id = ""
route = ""
workers_dev = true

[vars]
api_route = "<BASE ENDPOINT FOR FPJS>"

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"
