name: Check coverage for PR

on:
  pull_request:

jobs:
  run-tests-check-coverage:
    runs-on: ubuntu-20.04
    name: Run tests & check coverage
    steps:
      - uses: actions/checkout@v3

#      - name: Install node
#        uses: actions/setup-node@v3
#        with:
#          node-version-file: '.node-version'
#      - name: Cache
#        uses: actions/cache@v2
#        with:
#          path: node_modules
#          key: nodemodules-${{ hashFiles('yarn.lock') }}
#          restore-keys: nodemodules-
#      - name: Install Dependencies and prepare packages
#        run: yarn install
#        env:
#          CI: true
#      - name: Run test
#        run: yarn test
      - name: Jest coverage comment
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn



