name: Release

on:
  workflow_dispatch:


jobs:
  release:
    name: Release new version
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '18' # This workflow ignores node-version-file because semantic-release requires node 18 and cloudflare-wrangler-action requires node 16

      - name: Install Node packages
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Type check
        run: yarn test:dts
      - name: Install release dependencies
        run: yarn install --cwd=release
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@91ab76a4a393a8d0c4739e9aea1818b56bc953ea
        with:
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/exec@6.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          HUSKY: 0