name: Update worker's repository from the public template

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Get updates from the public template and merge into the repository branch
        uses: sshelomentsev/update-repository@v1.2.0        
        with:
          source: https://github.com/fingerprintjs/fingerprintjs-pro-cloudflare-worker.git
          branch: master
